---
- hosts: localhost
  tasks:
  - name: install openjdk8
    apt: update_cache=yes
    apt: name=openjdk-8-jdk state=present

  - name: import es pgp key
    raw: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

  - name: install apt repo
    apt: name=apt-transport-https state=present

  - name: add es repo
    raw: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list

  - name: install es
    apt: update_cache=yes ache_valid_time=3600
    apt: name=elasticsearch state=present

  - name: Update elasticsearch configuration file
    replace:
      dest: "/etc/elasticsearch/elasticsearch.yml"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - { regexp: '#network.host: 192.168.0.1', replace: 'network.host: localhost' }
      - { regexp: '#http.port: 9200', replace: 'http.port: 9200' }
    become: yes

  - name: Ensure ES is running (and enable it at boot)
    service: name=elasticsearch state=started enabled=yes
